-- CreateTable
CREATE TABLE "protocol_contributors_20240212_1" (
    "_id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "repo" STRING,
    "login" STRING,
    "github_id" INT8,
    "node_id" STRING,
    "contributions" INT8,
    "type" STRING,
    "updated_at" INT8,

    CONSTRAINT "protocol_contributors_20240212_1_pkey" PRIMARY KEY ("_id")
);

-- CreateTable
CREATE TABLE "protocol_engineers_emails_20240301" (
    "_id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "username" STRING,
    "email" STRING,
    "commit_email_counts" JSONB,
    "updated_at" INT8,

    CONSTRAINT "protocol_engineers_emails_20240301_pkey" PRIMARY KEY ("_id")
);

-- CreateTable
CREATE TABLE "protocol_engineers_user_info_20240229_2150" (
    "_id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING,
    "login" STRING,
    "location" STRING,
    "websiteUrl" STRING,
    "bio" STRING,
    "company" STRING,
    "socialAccounts" JSONB,
    "repositories" JSONB,
    "follower_count" INT8,
    "totalCommitContributions" INT8,
    "totalPullRequestReviewContributions" INT8,
    "totalPullRequests" INT8,
    "totalOpenIssues" INT8,
    "totalClosedIssues" INT8,
    "totalRepositoriesContributedTo" INT8,
    "unique_languages" JSONB,
    "total_languages_sizes" JSONB,
    "location_details" JSONB,
    "country_code" STRING,
    "updated_at" INT8,

    CONSTRAINT "protocol_engineers_user_info_20240229_2150_pkey" PRIMARY KEY ("_id")
);

-- CreateTable
CREATE TABLE "protocol_engineers_user_info_20240301_1717" (
    "_id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING,
    "login" STRING,
    "location" STRING,
    "websiteUrl" STRING,
    "bio" STRING,
    "company" STRING,
    "socialAccounts" JSONB,
    "repositories" JSONB,
    "follower_count" INT8,
    "totalCommitContributions" INT8,
    "totalPullRequestReviewContributions" INT8,
    "totalPullRequests" INT8,
    "totalOpenIssues" INT8,
    "totalClosedIssues" INT8,
    "totalRepositoriesContributedTo" INT8,
    "unique_languages" JSONB,
    "total_languages_sizes" JSONB,
    "location_details" JSONB,
    "country_code" STRING,
    "updated_at" INT8,

    CONSTRAINT "protocol_engineers_user_info_20240301_1717_pkey" PRIMARY KEY ("_id")
);

-- CreateTable
CREATE TABLE "repository_details" (
    "_id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "github_id" INT8,
    "github_node_id" STRING,
    "github_name" STRING,
    "is_private" BOOL,
    "description" STRING,
    "is_fork" BOOL,
    "github_created_at" STRING,
    "github_updated_at" STRING,
    "github_pushed_at" STRING,
    "stargazers_count" INT8,
    "language" STRING,
    "forks_count" INT8,
    "mirror_url" STRING,
    "is_archived" BOOL,
    "is_disabled" BOOL,
    "open_issues_count" INT8,
    "github_topics" JSONB,
    "visibility" STRING,
    "default_branch" STRING,
    "network_count" INT8,
    "subscribers_count" INT8,
    "owner_loging" STRING,
    "owner_id" INT8,
    "owner_node_id" STRING,
    "owner_avatar_url" STRING,
    "owner_type" STRING,
    "updated_at" INT8,

    CONSTRAINT "repository_details_pkey" PRIMARY KEY ("_id")
);

-- CreateTable
CREATE TABLE "repo_contributors" (
    "id" INT8 NOT NULL DEFAULT unique_rowid(),
    "repository" STRING NOT NULL,
    "contributor" STRING NOT NULL,
    "contributions" INT8,
    "created_at" INT8 NOT NULL DEFAULT (extract('epoch'::STRING, now()) * 1000.0)::INT8,
    "updated_at" INT8 NOT NULL DEFAULT (extract('epoch'::STRING, now()) * 1000.0)::INT8,

    CONSTRAINT "repo_contributors_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "repositories" (
    "id" INT8 NOT NULL DEFAULT unique_rowid(),
    "org_repository" STRING NOT NULL,
    "manual_tags" STRING[],
    "contributors_last_fetched_at" INT8,
    "created_at" INT8 NOT NULL DEFAULT (extract('epoch'::STRING, now()) * 1000.0)::INT8,
    "updated_at" INT8 NOT NULL DEFAULT (extract('epoch'::STRING, now()) * 1000.0)::INT8,
    "github_id" STRING,
    "github_node_id" STRING,
    "github_name" STRING,
    "is_private" BOOL DEFAULT false,
    "repository_owner" STRING,
    "description" STRING,
    "is_fork" BOOL NOT NULL DEFAULT false,
    "github_created_at" STRING,
    "github_updated_at" STRING,
    "gitub_pushed_at" STRING,
    "github_size" INT8,
    "stargazers_counts" INT8,
    "github_language" STRING,
    "forks_counts" INT8,
    "mirror_url" STRING,
    "is_archived" BOOL DEFAULT false,
    "is_disabled" BOOL DEFAULT false,
    "open_issues_counts" INT8,
    "github_topics" STRING[],
    "visibility" STRING,
    "default_branch" STRING,
    "network_count" INT8,
    "subscribers_count" INT8,
    "details_last_fetched_at" INT8,

    CONSTRAINT "repositories_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "repository_owner" (
    "id" INT8 NOT NULL DEFAULT unique_rowid(),
    "github_login" STRING NOT NULL,
    "github_id" STRING,
    "github_node_id" STRING,
    "github_avatar_url" STRING,
    "github_type" STRING,
    "created_at" INT8 NOT NULL DEFAULT (extract('epoch'::STRING, now()) * 1000.0)::INT8,
    "updated_at" INT8 NOT NULL DEFAULT (extract('epoch'::STRING, now()) * 1000.0)::INT8,

    CONSTRAINT "repository_owner_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "users" (
    "id" INT8 NOT NULL DEFAULT unique_rowid(),
    "username" STRING NOT NULL,
    "display_name" STRING,
    "email_id" STRING,
    "user_type" STRING NOT NULL,
    "github_website_url" STRING,
    "github_bio" STRING,
    "github_social_accounts" STRING,
    "github_location" STRING,
    "location_country_code" STRING,
    "location_details" STRING,
    "github_user_id" STRING,
    "github_node_id" STRING,
    "github_bio_last_updated_at" INT8,
    "created_at" INT8 NOT NULL DEFAULT (extract('epoch'::STRING, now()) * 1000.0)::INT8,
    "updated_at" INT8 NOT NULL DEFAULT (extract('epoch'::STRING, now()) * 1000.0)::INT8,
    "commit_email_counts" JSONB,
    "email_updated_at" INT8,
    "profile_source" JSONB,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "repositories_org_repository_key" ON "repositories"("org_repository");

-- CreateIndex
CREATE UNIQUE INDEX "repositories_github_id_key" ON "repositories"("github_id");

-- CreateIndex
CREATE UNIQUE INDEX "repositories_github_node_id_key" ON "repositories"("github_node_id");

-- CreateIndex
CREATE UNIQUE INDEX "repository_owner_github_login_key" ON "repository_owner"("github_login");

-- CreateIndex
CREATE UNIQUE INDEX "repository_owner_github_id_key" ON "repository_owner"("github_id");

-- CreateIndex
CREATE UNIQUE INDEX "users_username_key" ON "users"("username");

-- AddForeignKey
ALTER TABLE "repo_contributors" ADD CONSTRAINT "repo_contributors_contributor_fkey" FOREIGN KEY ("contributor") REFERENCES "users"("username") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "repo_contributors" ADD CONSTRAINT "repo_contributors_repository_fkey" FOREIGN KEY ("repository") REFERENCES "repositories"("org_repository") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "repositories" ADD CONSTRAINT "repositories_repository_owner_fkey" FOREIGN KEY ("repository_owner") REFERENCES "repository_owner"("github_login") ON DELETE NO ACTION ON UPDATE NO ACTION;

